### ISSUE TITLE
Cyrillic characters are not supported

### ISSUE THREAD

**Issue by x09** [reduf/search#29]
![изображение](https://github.com/reduf/search/assets/1303927/d205d12f-21b6-4239-a9f0-f0d30fab8d7d)

**Comment by reduf** [comment]
I added some support in `v0.9.0`.

The font isn't great, but I'm not really sure what I can use and ship with the tool. I'm openned to recommendations.

**Comment by reduf** [comment]
Btw, if you can try and give me a feedbacks on whether it works, I would very much appreciate it :)
