### ISSUE TITLE
feature request: option to use default windows file handler

### ISSUE THREAD

**Issue by Mattwmaster58** [reduf/search#31]
This is the default with Everything by voidtools, which is where I got the idea from. I would find it useful as I use a few different IDEs with different file associations.

**Comment by reduf** [comment]
I will look into it, it should be pretty straightforward with `ShellExecuteW`.

**Comment by reduf** [comment]
@Mattwmaster58 It should now be possible (commit: 45c6f69954589840fb692af69ccc4bbba21690e8) by simply changing the settings for the editor to `System`. Please test it and give feedbacks.

**Comment by Mattwmaster58** [comment]
I would love to test, but after installing cargo/mingw g++, still was unable to build with the amount of time I had. Will have to wait for the GH release unless I find some time to diagnose the build.

**Comment by reduf** [comment]
Will be great. Are you building on Linux? If yes, then this won't do anything, if you're on Windows, then "cargo build" should work. Maybe you need msvc... In any case, if you're on Windows, I can build it too.

**Comment by Mattwmaster58** [comment]
I do have MSVC and gcc as far as I know, but I'm getting 1 billion

```
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          collect2.exe: error: ld returned 5 exit status


error: could not compile `search` (bin "search") due to 1 previous error
```
type errors trying to build. Yes, on windows.

**Comment by reduf** [comment]
Weird... I personally just do `cargo build` or `cargo build --release` from the root of the project. Is that what you did?

In any case, here is a compiled version.
[search.zip](https://github.com/user-attachments/files/16478714/search.zip)

**Comment by Mattwmaster58** [comment]
Getting this error:
`Failed to edit: '<path>' with the shell, err: OS { code: 1155, ... message: "No application is associated with the specified file for this operation." }`

Meanwhile, within Windows Explorer, I can see these associations:
![image](https://github.com/user-attachments/assets/250f4c09-b7ef-4ed9-8171-1c2cd327fc26)
![image](https://github.com/user-attachments/assets/4003137a-12a2-4cea-9234-b00daf5bdd30)

And indeed, double clicking the file, or "running" it in a powershell window has VSC opening that type of file.

**Comment by reduf** [comment]
Interesting, I explicitly choose the `"edit"` verb as it seemed more correct, but you're likey right and it should be null. I will fix that.

**Comment by reduf** [comment]
[search.zip](https://github.com/user-attachments/files/16514041/search.zip)

Here is a new build with the verb set to `null`.

**Comment by Mattwmaster58** [comment]
Works great. Test few different programming languages as well as PDFs and DOCX. At first thought it was broken, but it was just my VSC installation failing to open the file :)

**Comment by ldufresnegs** [comment]
Sounds good, the only thing I'm a bit unsatisfied with is that it can start an executable. It's somewhat hard, because by default the lib I use to search will detect it as binary file and skip it.
